import {Inter, Montserrat} from "next/font/google";
import "./globals.css";
import 'swiper/css';
import Layout from "@/layout/layout";
import Head from "next/head";
const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({
    subsets:["cyrillic" ,"latin"] ,
    weight: ['400'],
    variable: "--font-montserrat",
    display:'swap'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <Head>
            <title>Hello world</title>
        </Head>
      <body className={`overflow-x-hidden !font-montserrat ${montserrat.variable}`} >
        <Layout children={children}/>
      </body>
    </html>
  );
}
